// Static demo data used ONLY on public pages (Examples, HomePage)
// These are display-only and never hit the backend

export const demoCharacters = [
  {
    id: 'demo-1',
    name: 'Amira',
    role: 'Protagonist',
    ageRange: '7-10',
    status: 'approved' as const,
    imageUrl: '/demo/characters/amira.png',
    traits: ['brave', 'curious', 'kind'],
    speechStyle: 'Thoughtful and gentle',
  },
  {
    id: 'demo-2',
    name: 'Omar',
    role: 'Supporting',
    ageRange: '8-11',
    status: 'locked' as const,
    imageUrl: '/demo/characters/omar.png',
    traits: ['loyal', 'funny', 'energetic'],
    speechStyle: 'Cheerful and enthusiastic',
  },
  {
    id: 'demo-3',
    name: 'Fatima',
    role: 'Mentor',
    ageRange: 'Adult',
    status: 'approved' as const,
    imageUrl: '/demo/characters/fatima.png',
    traits: ['wise', 'patient', 'nurturing'],
    speechStyle: 'Calm and wise',
  },
  {
    id: 'demo-4',
    name: 'Yusuf',
    role: 'Supporting',
    ageRange: '6-9',
    status: 'draft' as const,
    imageUrl: '/demo/characters/yusuf.png',
    traits: ['honest', 'playful'],
    speechStyle: 'Direct and honest',
  },
  {
    id: 'demo-5',
    name: 'Zainab',
    role: 'Protagonist',
    ageRange: '5-8',
    status: 'approved' as const,
    imageUrl: '/demo/characters/zainab.png',
    traits: ['creative', 'imaginative'],
    speechStyle: 'Imaginative and expressive',
  },
  {
    id: 'demo-6',
    name: 'Ibrahim',
    role: 'Mentor',
    ageRange: 'Adult',
    status: 'locked' as const,
    imageUrl: '/demo/characters/ibrahim.png',
    traits: ['scholarly', 'patient'],
    speechStyle: 'Scholarly and warm',
  },
];

export const demoBooks = [
  {
    id: 'demo-book-1',
    title: 'The Stars of Ramadan',
    author: 'Amira Hassan',
    ageRange: '4-7',
    category: 'values',
    coverUrl: '/demo/covers/ramadan-amira.png',
  },
  {
    id: 'demo-book-2',
    title: 'The Mountain of Patience',
    author: 'Noor Studio',
    ageRange: '8-12',
    category: 'adventure',
    coverUrl: '/demo/covers/mountain-patience.png',
  },
  {
    id: 'demo-book-3',
    title: 'The Generous Traveler',
    author: 'Noor Studio',
    ageRange: '5-8',
    category: 'values',
    coverUrl: '/demo/covers/generous-traveler.png',
  },
  {
    id: 'demo-book-4',
    title: "Learning Wudu with Omar",
    author: 'Noor Studio',
    ageRange: '4-7',
    category: 'educational',
    coverUrl: '/demo/covers/wudu-omar.png',
  },
  {
    id: 'demo-book-5',
    title: "The Prophet's Garden",
    author: 'Noor Studio',
    ageRange: '6-10',
    category: 'seerah',
    coverUrl: '/demo/covers/prophets-garden.png',
  },
  {
    id: 'demo-book-6',
    title: 'Kindness in the Souk',
    author: 'Noor Studio',
    ageRange: '4-7',
    category: 'values',
    coverUrl: '/demo/covers/souk-kindness.png',
  },
];
